# permissions for end users to edit s3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3-editor-role
rules:
- apiGroups:
  - aws.platform.operatorhello.com
  resources:
  - s3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.platform.operatorhello.com
  resources:
  - s3s/status
  verbs:
  - get
