# permissions for end users to view s3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3-viewer-role
rules:
- apiGroups:
  - aws.platform.operatorhello.com
  resources:
  - s3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.platform.operatorhello.com
  resources:
  - s3s/status
  verbs:
  - get
